version: '2'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - 9000:9000
        volumes:
            - /var/wwww/html/pixel-leadgrease:/var/www/html/pixel-leadgrease
        networks:
            - symfony

networks:
    symfony:
